### ISSUE TITLE
Support bare vCloud Director 5.5

### ISSUE THREAD

**Issue by rickard-von-essen** [vmware-archive/govcloudair#1]
Hi! 

I would like to use this lib against "bare" vCloud Director 5.5. I've done some hacking and gotten it to work with some changes in the client initialization. 

If you are interested I can sanitize the solution and open a PR, if you are willing to support this. 

PS. My use case is that I want to build vcd support for Packer and terraform. It would be awesome if you could share your progress on a terraform provider.

**Comment by mattbostock** [comment]
Have you done any work yet on the Terraform plugin?

**Comment by robcoward** [comment]
Guess that this can be closed by #32

**Comment by rickard-von-essen** [comment]
Fixed in #32
