### ISSUE TITLE
Compute ID in Authenticate function

### ISSUE THREAD

**Issue by karthequian** [vmware-archive/govcloudair#3]
I have a question about the computeid and vdcid parameters in the Authenticate function:
https://github.com/vmware/govcloudair/blob/master/api.go#L268

I have a vcloud air account, and when I login to my vcloud air dashboard, I can fetch the "vdcid" from the ID of my virtual data center; however, where do I get the "computeid" parameter inside the vcloud air UI?

After browsing the code, I realized that the vdcid and computeid ended up being the same value in my usecase- is this always true for vcloud air authentication?

Thank you in advance!

**Comment by frapposelli** [comment]
`computeid` is only needed when using the Dedicated Cloud offering, if using a Virtual Private Cloud `vdcid` is sufficient.

**Comment by karthequian** [comment]
+1 Thanks for the info @frapposelli!
